### PR TITLE
Re-creation on Newsweek using Bootstrap

### PR DESCRIPTION
**Pull request by moinkhanif**
We were to recreate the Newsweek website. The above is my version of the website

Features:

- Made using Bootstrap

* Used minimal to no javascript

* Top Asides are sticky untill their content is further scrolled.

* Responsive in nature

* Used fontawesome for icons

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Moin!
### Everything looks good :+1: 
### The readme file is very descriptive!

### But your project needs a few changes before it can be approved.

Kindly recommended to use Bootstrap CSS classes everywhere for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) 


screen

* Please fix this part on a small screen. In your version of the project it looks so:


* In original version it looks like:





### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Wow! You've done a near perfect job! @moinkhanif 
This is so beautiful and all the hard work you put in is showing. However, the section @Anna-Myzukina made comments about still has issues, especially in tablet mode. Can you give this another look?

Please request anoanother review once this is done 😊

**Comment by moinkhanif** [comment]
Ahh Yea! @Oluwadamilareolusakin @Anna-Myzukina , I finally fixed it 😅 Thank you.

**Comment by kobiyoyo** [comment]
### Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @Moinkhanif ,  You have done a great job with this project. :clap:

**Pull request merged**
